import { playProfileSynth } from "@core/profile_synth";

export const AXE_HIT_PROFILES = Object.freeze([
  Object.freeze({
    type: "oscillator",
    description: "Deep axe impact thud: kept from the previous version because the weight feels right.",
    startOffset: 0,
    duration: 0.11,
    gain: 0.42,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 95,
    sweepEnabled: true,
    frequencyEnd: 42,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 360,
        q: 0.9,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Initial dense impact slap: low-mid wet contact under the thud, like the axe head biting into thick material.",
    noiseType: "pink",
    startOffset: 0,
    duration: 0.075,
    gain: 0.72,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 720,
    q: 1.6,
    sweepEnabled: true,
    frequencyEnd: 380,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.018,
        feedback: 0.08,
        mix: 0.08,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Primary splinter crack: sharp woody fracture right after impact.",
    noiseType: "white",
    startOffset: 0.006,
    duration: 0.036,
    gain: 0.44,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 2200,
    q: 4.6,
    sweepEnabled: true,
    frequencyEnd: 950,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 14,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3600,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "High splinter shard: a fast brittle snap like wood or bone cracking loose.",
    noiseType: "white",
    startOffset: 0.018,
    duration: 0.026,
    gain: 0.3,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 3200,
    q: 5,
    sweepEnabled: true,
    frequencyEnd: 1400,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 10,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 4800,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Ripping splinter bed: continuous rough grain tearing under the cracks, making the impact feel like fibers are being ripped apart.",
    noiseType: "white",
    startOffset: 0.032,
    duration: 0.19,
    gain: 0.36,
    attackTime: 0.004,
    decayCurve: "linear",
    filterType: "bandpass",
    frequency: 1350,
    q: 3.1,
    sweepEnabled: true,
    frequencyEnd: 620,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 16,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3000,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.012,
        feedback: 0.13,
        mix: 0.12,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "First ripping splinter pull: broader than a click, like a strip of wood or tissue tearing open.",
    noiseType: "white",
    startOffset: 0.052,
    duration: 0.072,
    gain: 0.34,
    attackTime: 0.002,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1250,
    q: 3.7,
    sweepEnabled: true,
    frequencyEnd: 760,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 12,
        oversample: "2x",
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.01,
        feedback: 0.14,
        mix: 0.12,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Second ripping splinter pull: lower rough tear that overlaps the first so the break feels continuous.",
    noiseType: "white",
    startOffset: 0.095,
    duration: 0.085,
    gain: 0.3,
    attackTime: 0.003,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 980,
    q: 3.5,
    sweepEnabled: true,
    frequencyEnd: 520,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 11,
        oversample: "2x",
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.013,
        feedback: 0.12,
        mix: 0.11,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Late brittle split: delayed crack detail after the axe is already buried, suggesting the target splitting apart.",
    noiseType: "white",
    startOffset: 0.145,
    duration: 0.05,
    gain: 0.22,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1700,
    q: 4.2,
    sweepEnabled: true,
    frequencyEnd: 760,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 9,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3300,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Thick wet gore body: lowpass pink noise that blooms after impact, keeping the splintering sound wet and heavy.",
    noiseType: "pink",
    startOffset: 0.025,
    duration: 0.24,
    gain: 0.48,
    attackTime: 0.018,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 620,
    q: 2.2,
    sweepEnabled: true,
    frequencyEnd: 260,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.032,
        feedback: 0.12,
        mix: 0.14,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Wet gouging drag: rough low-mid scrape as the axe continues through the target after the initial hit.",
    noiseType: "pink",
    startOffset: 0.065,
    duration: 0.22,
    gain: 0.39,
    attackTime: 0.006,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 360,
    q: 2.9,
    sweepEnabled: true,
    frequencyEnd: 760,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.018,
        feedback: 0.1,
        mix: 0.1,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Wet tearing pull: broad fibrous gore rip after the thud, blended under the splintering so it feels like wet material tearing apart.",
    noiseType: "pink",
    startOffset: 0.105,
    duration: 0.13,
    gain: 0.38,
    attackTime: 0.004,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 480,
    q: 2.7,
    sweepEnabled: true,
    frequencyEnd: 980,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.02,
        feedback: 0.11,
        mix: 0.11,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Short heavy wet tail: lets the axe impact decay with a thick gore smear after the ripping splintering.",
    noiseType: "pink",
    startOffset: 0.19,
    duration: 0.16,
    gain: 0.25,
    attackTime: 0.012,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 420,
    q: 1.4,
    sweepEnabled: true,
    frequencyEnd: 210,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.038,
        feedback: 0.1,
        mix: 0.12,
      }),
    ]),
  }),
]);

export const playAxeHit = (profiles = AXE_HIT_PROFILES) => {
  playProfileSynth(profiles);
};
