export default Object.freeze({
  arc: Math.PI / 2,
  cooldown: 23,
  criticalChance: 0.08,
  criticalMultiplier: 2,
  damageMax: 5,
  damageMin: 3,
  damageProfile: Object.freeze({ slashing: 0.9, crushing: 0.1 }),
  damageType: "slashing",
  duration: 9,
  handedness: "oneHanded",
  knockback: 34,
  range: 50,
  staminaCost: 145,
});
