import { playProfileSynth } from "@core/profile_synth";

export const FIST_HIT_PROFILES = Object.freeze([
  Object.freeze({
    type: "oscillator",
    description: "Heavier body thud: deep and loud short impact tone that makes the punch land with real torso weight.",
    startOffset: 0,
    duration: 0.16,
    gain: 0.66,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 72,
    sweepEnabled: true,
    frequencyEnd: 32,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 280,
        q: 0.9,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Low brown thud support: very low dark noise under the main thud, adding chesty weight without a sharp attack.",
    noiseType: "brown",
    startOffset: 0,
    duration: 0.18,
    gain: 0.34,
    attackTime: 0.004,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 210,
    q: 1.1,
    sweepEnabled: true,
    frequencyEnd: 75,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 180,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "oscillator",
    description: "Upper body punch: short low-mid layer that adds chesty impact above the deep thud.",
    startOffset: 0.003,
    duration: 0.095,
    gain: 0.32,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 145,
    sweepEnabled: true,
    frequencyEnd: 68,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 480,
        q: 0.9,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Heavy skin contact slap: quick lowpass pink-noise smack from fist hitting flesh or cloth.",
    noiseType: "pink",
    startOffset: 0,
    duration: 0.085,
    gain: 0.7,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 680,
    q: 1.45,
    sweepEnabled: true,
    frequencyEnd: 280,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.014,
        feedback: 0.07,
        mix: 0.07,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Dense torso compression: louder low-mid pressure layer so the punch feels like it sinks into the body.",
    noiseType: "pink",
    startOffset: 0.01,
    duration: 0.18,
    gain: 0.52,
    attackTime: 0.006,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 230,
    q: 2.3,
    sweepEnabled: true,
    frequencyEnd: 95,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 6,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 760,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.024,
        feedback: 0.08,
        mix: 0.07,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Crash layer on impact: broad midrange burst on top of the body thud, like gear, cloth, or the target jolting from the hit.",
    noiseType: "white",
    startOffset: 0.006,
    duration: 0.115,
    gain: 0.28,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 820,
    q: 1.35,
    sweepEnabled: true,
    frequencyEnd: 320,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 7,
        oversample: "2x",
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.026,
        feedback: 0.16,
        mix: 0.13,
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1900,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Secondary crash grit: delayed lower crash detail so the impact feels more devastating without sounding metallic.",
    noiseType: "pink",
    startOffset: 0.04,
    duration: 0.16,
    gain: 0.22,
    attackTime: 0.005,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 480,
    q: 1.8,
    sweepEnabled: true,
    frequencyEnd: 180,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 5,
        oversample: "2x",
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.034,
        feedback: 0.12,
        mix: 0.1,
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1100,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Knuckle bite: small dry midrange contact detail so the punch has a fist edge, not only a soft thump.",
    noiseType: "white",
    startOffset: 0.006,
    duration: 0.028,
    gain: 0.16,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 950,
    q: 2.6,
    sweepEnabled: true,
    frequencyEnd: 520,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1800,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Flesh rebound: damp after-smack as the fist compresses and releases from the target.",
    noiseType: "pink",
    startOffset: 0.055,
    duration: 0.11,
    gain: 0.24,
    attackTime: 0.008,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 500,
    q: 1.25,
    sweepEnabled: true,
    frequencyEnd: 200,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.022,
        feedback: 0.08,
        mix: 0.08,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Breathy crash tail: faint short air/body decay after the hit, helping the crash layer settle naturally.",
    noiseType: "pink",
    startOffset: 0.1,
    duration: 0.15,
    gain: 0.12,
    attackTime: 0.014,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 380,
    q: 1.35,
    sweepEnabled: true,
    frequencyEnd: 140,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([]),
  }),
]);

export const playFistHit = (profiles = FIST_HIT_PROFILES) => {
  playProfileSynth(profiles);
};
