import { playProfileSynth } from "@core/profile_synth";

export const DAGGER_SWING_PROFILES = Object.freeze([
  Object.freeze({
    type: "noise_filter",
    filterType: "highpass",
    frequency: 6601,
    q: 6,
    reverseBuffer: true,
    muted: false,
    startOffset: 0,
    duration: 0.08,
    gain: 0.08,
    effects: Object.freeze([
      Object.freeze({
        type: "reverb",
        duration: 0.08,
        decay: 4.7,
        mix: 1,
      }),
      Object.freeze({
        type: "distortion",
        amount: 183,
        oversample: "4x",
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    filterType: "bandpass",
    frequency: 3823,
    q: 6,
    reverseBuffer: true,
    muted: false,
    startOffset: 0.02,
    duration: 0.6,
    gain: 0.22,
    effects: Object.freeze([
      Object.freeze({
        type: "reverb",
        duration: 0.08,
        decay: 4.7,
        mix: 1,
      }),
      Object.freeze({
        type: "distortion",
        amount: 313,
        oversample: "4x",
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    filterType: "lowpass",
    frequency: 2440,
    q: 6,
    reverseBuffer: true,
    muted: false,
    startOffset: 0.04,
    duration: 0.04,
    gain: 0.13,
    effects: Object.freeze([
      Object.freeze({
        type: "reverb",
        duration: 0.08,
        decay: 4.7,
        mix: 1,
      }),
      Object.freeze({
        type: "distortion",
        amount: 313,
        oversample: "4x",
      }),
    ]),
  }),
]);

export const DAGGER_HIT_PROFILES = Object.freeze([
  Object.freeze({
    type: "noise_filter",
    description: "Higher wet initial bite: a thicker high-mid entry that feels like the blade catching flesh before gouging through.",
    noiseType: "pink",
    startOffset: 0,
    duration: 0.045,
    gain: 0.62,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1100,
    q: 2.5,
    sweepEnabled: true,
    frequencyEnd: 2050,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3600,
        q: 0.9,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.008,
        feedback: 0.14,
        mix: 0.12,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Main stronger gouging drag: dense wet friction that starts lower than the bite and scrapes upward through flesh.",
    noiseType: "pink",
    startOffset: 0.008,
    duration: 0.17,
    gain: 0.84,
    attackTime: 0.005,
    decayCurve: "linear",
    filterType: "bandpass",
    frequency: 620,
    q: 3.1,
    sweepEnabled: true,
    frequencyEnd: 1780,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3150,
        q: 0.9,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.01,
        feedback: 0.2,
        mix: 0.17,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Wet body smear: slightly higher slick lowpass body that fills in the gouge without adding thud.",
    noiseType: "pink",
    startOffset: 0.016,
    duration: 0.165,
    gain: 0.58,
    attackTime: 0.006,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 1180,
    q: 1.7,
    sweepEnabled: true,
    frequencyEnd: 2200,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.015,
        feedback: 0.15,
        mix: 0.16,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "First hard gouge pull: broad wet tearing accent with more scrape and bite than a normal slice.",
    noiseType: "pink",
    startOffset: 0.032,
    duration: 0.055,
    gain: 0.72,
    attackTime: 0.0018,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 960,
    q: 3.5,
    sweepEnabled: true,
    frequencyEnd: 2450,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3900,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.009,
        feedback: 0.18,
        mix: 0.15,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Second hard gouge pull: overlapping fibrous drag, pitched slightly higher to make the gouge more audible.",
    noiseType: "pink",
    startOffset: 0.068,
    duration: 0.06,
    gain: 0.66,
    attackTime: 0.0022,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 820,
    q: 3.3,
    sweepEnabled: true,
    frequencyEnd: 2250,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.01,
        feedback: 0.17,
        mix: 0.14,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Third hard gouge pull: late wet scrape that keeps the sound gouging instead of just slicing.",
    noiseType: "pink",
    startOffset: 0.108,
    duration: 0.058,
    gain: 0.56,
    attackTime: 0.0028,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 720,
    q: 3,
    sweepEnabled: true,
    frequencyEnd: 2050,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.012,
        feedback: 0.14,
        mix: 0.12,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Short gouging grit layer: adds rough scraped texture through the middle of the hit without extending the total duration.",
    noiseType: "white",
    startOffset: 0.055,
    duration: 0.09,
    gain: 0.18,
    attackTime: 0.003,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1600,
    q: 2.2,
    sweepEnabled: true,
    frequencyEnd: 2600,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 4200,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Wet finishing drag: short slick tail that finishes higher, like the gouge lifting out of flesh.",
    noiseType: "pink",
    startOffset: 0.135,
    duration: 0.065,
    gain: 0.48,
    attackTime: 0.004,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 1500,
    q: 1.3,
    sweepEnabled: true,
    frequencyEnd: 2500,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.018,
        feedback: 0.11,
        mix: 0.13,
      }),
    ]),
  }),
]);

export const playDaggerSwing = (profiles = DAGGER_SWING_PROFILES) => {
  playProfileSynth(profiles);
};

export const playDaggerHit = (profiles = DAGGER_HIT_PROFILES) => {
  playProfileSynth(profiles);
};
