import { playProfileSynth } from "@core/profile_synth";

export const WOODEN_SHIELD_BLOCK_PROFILES = Object.freeze([
  Object.freeze({
    type: "oscillator",
    description: "Shield body thud: low blunt force from the weapon hitting a wooden shield face.",
    startOffset: 0,
    duration: 0.145,
    gain: 0.44,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 105,
    sweepEnabled: true,
    frequencyEnd: 48,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 360,
        q: 0.9,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Wooden impact slap: dry lowpass pink noise that makes the block feel broad and physical.",
    noiseType: "pink",
    startOffset: 0,
    duration: 0.09,
    gain: 0.66,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 640,
    q: 1.45,
    sweepEnabled: true,
    frequencyEnd: 280,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.02,
        feedback: 0.08,
        mix: 0.08,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Primary wood clock: loud dry knock from a weapon striking the wooden shield surface.",
    noiseType: "white",
    startOffset: 0.004,
    duration: 0.046,
    gain: 0.54,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 820,
    q: 5.1,
    sweepEnabled: true,
    frequencyEnd: 390,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1800,
        q: 0.9,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Hollow board clonk: lower resonant wooden knock, like a shield plank or board vibrating after the hit.",
    noiseType: "pink",
    startOffset: 0.01,
    duration: 0.075,
    gain: 0.38,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 460,
    q: 4.4,
    sweepEnabled: true,
    frequencyEnd: 260,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.026,
        feedback: 0.14,
        mix: 0.12,
      }),
    ]),
  }),
  Object.freeze({
    type: "oscillator",
    description: "Wood shield resonance: short hollow tonal body that makes the shield sound wooden rather than metallic.",
    startOffset: 0.012,
    duration: 0.19,
    gain: 0.18,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 420,
    sweepEnabled: true,
    frequencyEnd: 260,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "bandpass",
        frequency: 420,
        q: 4.7,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.032,
        feedback: 0.2,
        mix: 0.16,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Hard wood edge clack: sharper upper wood transient from the weapon catching the shield rim or hard grain.",
    noiseType: "white",
    startOffset: 0.018,
    duration: 0.034,
    gain: 0.24,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1300,
    q: 4.8,
    sweepEnabled: true,
    frequencyEnd: 720,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2500,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Primary splinter snap: sharp dry fracture as the shield grain starts to split under the block.",
    noiseType: "white",
    startOffset: 0.032,
    duration: 0.042,
    gain: 0.28,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1550,
    q: 5.4,
    sweepEnabled: true,
    frequencyEnd: 780,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 7,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3100,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Secondary splinter snap: lower delayed crack, like another plank fiber giving way after the first hit.",
    noiseType: "white",
    startOffset: 0.065,
    duration: 0.055,
    gain: 0.24,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 980,
    q: 4.6,
    sweepEnabled: true,
    frequencyEnd: 420,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 6,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2200,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.012,
        feedback: 0.08,
        mix: 0.08,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Wood grain tearing: rough dry scrape through the middle of the block, like stressed fibers splitting across the shield face.",
    noiseType: "white",
    startOffset: 0.075,
    duration: 0.12,
    gain: 0.2,
    attackTime: 0.004,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 760,
    q: 3.4,
    sweepEnabled: true,
    frequencyEnd: 320,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 8,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1700,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.018,
        feedback: 0.1,
        mix: 0.09,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Small high wood shards: quick brittle chips breaking away from the shield surface.",
    noiseType: "white",
    startOffset: 0.105,
    duration: 0.045,
    gain: 0.12,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1900,
    q: 5.2,
    sweepEnabled: true,
    frequencyEnd: 980,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 5,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3600,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Secondary board knock: delayed lower clocking detail as the shield flexes after the block.",
    noiseType: "white",
    startOffset: 0.075,
    duration: 0.045,
    gain: 0.18,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 620,
    q: 3.6,
    sweepEnabled: true,
    frequencyEnd: 300,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1500,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Dry shield decay: longer rough wooden tail, like the shield settling after the block and splinter stress.",
    noiseType: "pink",
    startOffset: 0.105,
    duration: 0.22,
    gain: 0.16,
    attackTime: 0.014,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 360,
    q: 2.1,
    sweepEnabled: true,
    frequencyEnd: 150,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.038,
        feedback: 0.1,
        mix: 0.1,
      }),
    ]),
  }),
]);

export const METAL_SHIELD_BLOCK_PROFILES = Object.freeze([
  Object.freeze({
    type: "noise_filter",
    description: "Sharper metal ding contact: bright initial tick from weapon striking shield plate.",
    noiseType: "white",
    startOffset: 0,
    duration: 0.024,
    gain: 0.46,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 3050,
    q: 5.2,
    sweepEnabled: true,
    frequencyEnd: 1700,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 4,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 6500,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "oscillator",
    description: "Main louder shield ping: clear ringing metal note with stronger reverb-like delay.",
    startOffset: 0.004,
    duration: 0.44,
    gain: 0.28,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "sine",
    frequency: 1650,
    sweepEnabled: true,
    frequencyEnd: 1320,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "bandpass",
        frequency: 1650,
        q: 6.2,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.052,
        feedback: 0.56,
        mix: 0.42,
      }),
    ]),
  }),
  Object.freeze({
    type: "oscillator",
    description: "Upper ding overtone: brighter harmonic that makes the bounce read as a metallic ding instead of a dull clank.",
    startOffset: 0.007,
    duration: 0.34,
    gain: 0.12,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "sine",
    frequency: 3300,
    sweepEnabled: true,
    frequencyEnd: 2550,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "bandpass",
        frequency: 3300,
        q: 6.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.036,
        feedback: 0.48,
        mix: 0.36,
      }),
    ]),
  }),
  Object.freeze({
    type: "oscillator",
    description: "Tiny high sparkle ping: very quiet top-end ring for extra shield shimmer.",
    startOffset: 0.012,
    duration: 0.24,
    gain: 0.045,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "sine",
    frequency: 5100,
    sweepEnabled: true,
    frequencyEnd: 3900,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "bandpass",
        frequency: 5100,
        q: 7.2,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.028,
        feedback: 0.36,
        mix: 0.28,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Reverberant shield shimmer: bright filtered noise with heavier delay to make the ring trail longer.",
    noiseType: "white",
    startOffset: 0.012,
    duration: 0.13,
    gain: 0.2,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 3900,
    q: 3.4,
    sweepEnabled: true,
    frequencyEnd: 2100,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.032,
        feedback: 0.5,
        mix: 0.4,
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 7200,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Rebound metal clack: small second contact as the weapon bounces away, also feeding the ring.",
    noiseType: "white",
    startOffset: 0.052,
    duration: 0.034,
    gain: 0.2,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 2200,
    q: 4.6,
    sweepEnabled: true,
    frequencyEnd: 1150,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 3,
        oversample: "2x",
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.038,
        feedback: 0.38,
        mix: 0.28,
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 4300,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Muted shield body: subtle low-mid plate response so the ping has physical mass and does not sound like a tiny bell.",
    noiseType: "pink",
    startOffset: 0,
    duration: 0.16,
    gain: 0.16,
    attackTime: 0.002,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 420,
    q: 2,
    sweepEnabled: true,
    frequencyEnd: 240,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.04,
        feedback: 0.16,
        mix: 0.14,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Long metallic ring tail: high-mid decay that extends the shield bounce reverb.",
    noiseType: "pink",
    startOffset: 0.09,
    duration: 0.42,
    gain: 0.1,
    attackTime: 0.016,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1500,
    q: 2.5,
    sweepEnabled: true,
    frequencyEnd: 760,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.06,
        feedback: 0.42,
        mix: 0.32,
      }),
    ]),
  }),
]);

export const playShieldBlock = (profiles = WOODEN_SHIELD_BLOCK_PROFILES) => {
  playProfileSynth(profiles);
};

export const playMetalShieldBlock = (profiles = METAL_SHIELD_BLOCK_PROFILES) => {
  playProfileSynth(profiles);
};
