export default Object.freeze({
  baseDetectDistance: 150,
  chaseSpeedModifier: 1,
  damageMax: 4,
  damageMin: 1,
  detectDistancePerEnemy: 20,
  drops: [
    { chance: 0.1, type: "coin" },
    { chance: 0.05, type: "hp_potion" },
  ],
  hitDistance: 32,
  hp: 50,
  hpVariance: 0.05,
  idleMaxFrames: 60,
  idlePauseChance: 0.5,
  idlePauseMax: 120,
  idlePauseMin: 30,
  idleSpeedModifier: 0.5,
  knockbackFactor: 0.4,
  respawnDelayMs: 5 * 60 * 1000,
  skeletonMagic: Object.freeze({
    castCooldownFrames: 90,
    castDistance: 140,
    castWindupFrames: 18,
    coldDurationFrames: 120,
    coldSpeedMultiplier: 0.75,
    projectileDamageMax: 8,
    projectileDamageMin: 2,
    projectileMaxDistance: 240,
    projectileSpeed: 6,
  }),
  spawn: {
    max: 614,
    min: 64,
  },
  speedMultiplier: 0.8,
  speedTransitionRate: 0.08,
  strength: 6,
  types: Object.freeze(["bat", "blob", "goblin", "skeleton"]),
  typeHp: Object.freeze({
    bat: 30,
    blob: 50,
    goblin: 70,
    skeleton: 20,
  }),
});
