import { playProfileSynth } from "@core/profile_synth";

export const GREATAXE_HIT_PROFILES = Object.freeze([
  Object.freeze({
    type: "oscillator",
    description: "Massive greataxe body thud: deeper and longer than the one-handed axe, giving the hit two-handed weight.",
    startOffset: 0,
    duration: 0.145,
    gain: 0.5,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 72,
    sweepEnabled: true,
    frequencyEnd: 32,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 300,
        q: 0.9,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Heavy wet impact slap: thick low-mid contact right as the greataxe bites into the target.",
    noiseType: "pink",
    startOffset: 0,
    duration: 0.105,
    gain: 0.78,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 560,
    q: 1.7,
    sweepEnabled: true,
    frequencyEnd: 260,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.022,
        feedback: 0.1,
        mix: 0.1,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Primary low splinter crack: a heavier woody/bony fracture, lower than the previous axe splinters.",
    noiseType: "white",
    startOffset: 0.008,
    duration: 0.052,
    gain: 0.46,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1350,
    q: 4.2,
    sweepEnabled: true,
    frequencyEnd: 520,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 16,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2800,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Secondary crushing split: lower delayed crack that suggests thick material buckling under the axe head.",
    noiseType: "white",
    startOffset: 0.035,
    duration: 0.065,
    gain: 0.36,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 980,
    q: 3.8,
    sweepEnabled: true,
    frequencyEnd: 430,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 13,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2300,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Ripping splinter bed: extended rough grain tearing, lower and longer so it feels like the target is being split open.",
    noiseType: "white",
    startOffset: 0.045,
    duration: 0.26,
    gain: 0.4,
    attackTime: 0.005,
    decayCurve: "linear",
    filterType: "bandpass",
    frequency: 920,
    q: 3.2,
    sweepEnabled: true,
    frequencyEnd: 420,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 18,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2500,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.014,
        feedback: 0.15,
        mix: 0.14,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Broad splinter tear one: a chunky pull of wood or bone fibers breaking apart after the first crack.",
    noiseType: "white",
    startOffset: 0.075,
    duration: 0.09,
    gain: 0.36,
    attackTime: 0.0025,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 860,
    q: 3.6,
    sweepEnabled: true,
    frequencyEnd: 390,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 14,
        oversample: "2x",
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.012,
        feedback: 0.15,
        mix: 0.13,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Broad splinter tear two: a second lower tearing pull, extending the sense of devastation.",
    noiseType: "white",
    startOffset: 0.135,
    duration: 0.105,
    gain: 0.32,
    attackTime: 0.003,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 720,
    q: 3.3,
    sweepEnabled: true,
    frequencyEnd: 330,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 12,
        oversample: "2x",
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.015,
        feedback: 0.13,
        mix: 0.12,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Late heavy split: delayed brittle crack after the main impact, like the target continuing to fracture.",
    noiseType: "white",
    startOffset: 0.215,
    duration: 0.06,
    gain: 0.24,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1100,
    q: 4,
    sweepEnabled: true,
    frequencyEnd: 480,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 10,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2500,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Thick wet gore body: lower, longer squelch bloom that makes the greataxe feel brutal and organic.",
    noiseType: "pink",
    startOffset: 0.03,
    duration: 0.32,
    gain: 0.52,
    attackTime: 0.02,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 520,
    q: 2.3,
    sweepEnabled: true,
    frequencyEnd: 210,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.036,
        feedback: 0.14,
        mix: 0.15,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Heavy gouging drag: low-mid scrape as the buried greataxe continues tearing through the target.",
    noiseType: "pink",
    startOffset: 0.085,
    duration: 0.3,
    gain: 0.43,
    attackTime: 0.008,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 300,
    q: 3,
    sweepEnabled: true,
    frequencyEnd: 660,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.02,
        feedback: 0.12,
        mix: 0.12,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Wet tearing gore pull: broad fibrous rip under the splintering, suggesting flesh and heavy fibers being torn open.",
    noiseType: "pink",
    startOffset: 0.15,
    duration: 0.18,
    gain: 0.4,
    attackTime: 0.005,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 390,
    q: 2.7,
    sweepEnabled: true,
    frequencyEnd: 850,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.023,
        feedback: 0.12,
        mix: 0.12,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Longer heavy wet tail: thick gore smear after the devastating greataxe blow, extending the decay slightly.",
    noiseType: "pink",
    startOffset: 0.27,
    duration: 0.22,
    gain: 0.28,
    attackTime: 0.016,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 360,
    q: 1.5,
    sweepEnabled: true,
    frequencyEnd: 170,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.044,
        feedback: 0.12,
        mix: 0.14,
      }),
    ]),
  }),
]);

export const playGreataxeHit = (profiles = GREATAXE_HIT_PROFILES) => {
  playProfileSynth(profiles);
};
