import { playProfileSynth } from "@core/profile_synth";

export const GREATHAMMER_HIT_PROFILES = Object.freeze([
  Object.freeze({
    type: "oscillator",
    description: "Huge blunt body thud: deep descending triangle tone that gives the greathammer its main two-handed weight.",
    startOffset: 0,
    duration: 0.24,
    gain: 0.82,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 54,
    sweepEnabled: true,
    frequencyEnd: 20,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 240,
        q: 0.9,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "oscillator",
    description: "Hard upper thud layer: short low-mid punch replacing the ping, making the hit feel like a solid hammer face slamming into dense material.",
    startOffset: 0.004,
    duration: 0.105,
    gain: 0.36,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 145,
    sweepEnabled: true,
    frequencyEnd: 72,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 520,
        q: 1,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Massive compression slap: dense lowpass impact noise that makes the target feel crushed flat at contact.",
    noiseType: "pink",
    startOffset: 0,
    duration: 0.18,
    gain: 1,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 390,
    q: 1.6,
    sweepEnabled: true,
    frequencyEnd: 120,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 18, oversample: "2x" }),
      Object.freeze({
        type: "delay",
        delayTime: 0.028,
        feedback: 0.12,
        mix: 0.12,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Hard face impact: short mid-low strike noise that adds a solid hammer-face smack instead of a ringing metallic ping.",
    noiseType: "white",
    startOffset: 0.006,
    duration: 0.045,
    gain: 0.34,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 620,
    q: 2.2,
    sweepEnabled: true,
    frequencyEnd: 260,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 10, oversample: "2x" }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1400,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Violent crash burst: wide debris-like noise right after impact, like armor, stone, and wreckage exploding outward.",
    noiseType: "white",
    startOffset: 0.006,
    duration: 0.26,
    gain: 0.54,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 620,
    q: 1.1,
    sweepEnabled: true,
    frequencyEnd: 190,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 16, oversample: "2x" }),
      Object.freeze({
        type: "delay",
        delayTime: 0.032,
        feedback: 0.22,
        mix: 0.18,
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1900,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "High splinter spray: brighter shards layered above the low crash, like small fragments cracking outward.",
    noiseType: "white",
    startOffset: 0.018,
    duration: 0.07,
    gain: 0.22,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1450,
    q: 3.4,
    sweepEnabled: true,
    frequencyEnd: 820,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 9, oversample: "2x" }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3000,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.013,
        feedback: 0.1,
        mix: 0.09,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Sharp splinter crackle: a shorter higher-frequency fracture detail that makes the destruction more jagged.",
    noiseType: "white",
    startOffset: 0.048,
    duration: 0.052,
    gain: 0.18,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1900,
    q: 4,
    sweepEnabled: true,
    frequencyEnd: 1050,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 8, oversample: "2x" }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3600,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Late bright splinter: delayed high shard detail so the target sounds like it continues cracking after the main hit.",
    noiseType: "white",
    startOffset: 0.118,
    duration: 0.065,
    gain: 0.14,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1350,
    q: 3.2,
    sweepEnabled: true,
    frequencyEnd: 720,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 7, oversample: "2x" }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2800,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.016,
        feedback: 0.08,
        mix: 0.08,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Deep crash wash: darker rubble collapse underneath the main crash, adding scale and aftershock.",
    noiseType: "pink",
    startOffset: 0.026,
    duration: 0.4,
    gain: 0.62,
    attackTime: 0.006,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 240,
    q: 1.7,
    sweepEnabled: true,
    frequencyEnd: 70,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 18, oversample: "2x" }),
      Object.freeze({
        type: "delay",
        delayTime: 0.052,
        feedback: 0.2,
        mix: 0.18,
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 800,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Primary heavy splinter break: chunky low fracture as the target gives way under the greathammer.",
    noiseType: "white",
    startOffset: 0.02,
    duration: 0.08,
    gain: 0.46,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 560,
    q: 3,
    sweepEnabled: true,
    frequencyEnd: 210,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 14, oversample: "2x" }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1200,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Secondary collapse splinter: delayed lower crack, like dense material buckling after the initial strike.",
    noiseType: "white",
    startOffset: 0.072,
    duration: 0.105,
    gain: 0.4,
    attackTime: 0.002,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 460,
    q: 2.8,
    sweepEnabled: true,
    frequencyEnd: 170,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 13, oversample: "2x" }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1050,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.014,
        feedback: 0.1,
        mix: 0.09,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Late crushing split: final delayed fracture so the hit feels like it continues breaking material inward.",
    noiseType: "white",
    startOffset: 0.15,
    duration: 0.12,
    gain: 0.3,
    attackTime: 0.0025,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 360,
    q: 2.6,
    sweepEnabled: true,
    frequencyEnd: 135,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 11, oversample: "2x" }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 850,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Crushing grind bed: sustained low grinding collapse that makes the impact feel devastating instead of just loud.",
    noiseType: "pink",
    startOffset: 0.038,
    duration: 0.42,
    gain: 0.74,
    attackTime: 0.01,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 210,
    q: 2.6,
    sweepEnabled: true,
    frequencyEnd: 70,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 18, oversample: "2x" }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 720,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.024,
        feedback: 0.14,
        mix: 0.12,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Muted metal mass scrape: low-mid scrape from the hammer head grinding across crushed material, metallic but not pingy.",
    noiseType: "white",
    startOffset: 0.055,
    duration: 0.16,
    gain: 0.2,
    attackTime: 0.004,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 880,
    q: 2,
    sweepEnabled: true,
    frequencyEnd: 420,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 10, oversample: "2x" }),
      Object.freeze({
        type: "delay",
        delayTime: 0.024,
        feedback: 0.14,
        mix: 0.1,
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1800,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Long devastation rubble tail: heavy crushed-material decay after the greathammer blow, extending the sense of aftermath.",
    noiseType: "pink",
    startOffset: 0.16,
    duration: 0.42,
    gain: 0.44,
    attackTime: 0.018,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 280,
    q: 1.35,
    sweepEnabled: true,
    frequencyEnd: 85,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 8, oversample: "2x" }),
      Object.freeze({
        type: "delay",
        delayTime: 0.06,
        feedback: 0.14,
        mix: 0.14,
      }),
    ]),
  }),
]);

export const playGreathammerHit = (profiles = GREATHAMMER_HIT_PROFILES) => {
  playProfileSynth(profiles);
};
