export default Object.freeze({
  cooldown: 11,
  criticalChance: 0.05,
  criticalMultiplier: 2,
  damageMax: 3,
  damageMin: 1,
  damageProfile: Object.freeze({ piercing: 1 }),
  damageType: "piercing",
  duration: 5,
  handedness: "oneHanded",
  knockback: 18,
  range: 25,
  staminaCost: 50,
  thrustWidth: 20,
});
