// Built-in starter recipes for the Sound Profile system. Used in two
// places by the sandbox:
//
//   1. As standalone library entries in the dropdown ("Library presets"
//      optgroup) so a user can audition each one and tune it in place.
//   2. As starting points when the user clicks "+ Add experimental sound"
//      and picks a template to seed the new entry's profiles.
//
// Each preset is a frozen array of Profile objects in the same shape as
// `DEFAULT_CLICK_PROFILES`. New presets here are picked up automatically
// by the install module's dropdown builder.

const freezeProfiles = (profiles) => Object.freeze(profiles.map((p) => Object.freeze(p)));

export const PRESETS = Object.freeze({
  blank: {
    label: "Blank",
    description: "Empty starting point with no profiles -- add your own",
    profiles: Object.freeze([]),
  },
  blip: {
    label: "Blip",
    description: "Short upper-mid sine pip, classic 8-bit menu blip",
    profiles: freezeProfiles([
      {
        type: "oscillator",
        startOffset: 0,
        duration: 0.08,
        gain: 0.2,
        oscillatorType: "square",
        frequency: 880,
      },
    ]),
  },
  boom: {
    label: "Boom",
    description: "Low sine thump plus a noise burst body",
    profiles: freezeProfiles([
      {
        type: "oscillator",
        startOffset: 0,
        duration: 0.4,
        gain: 0.4,
        oscillatorType: "sine",
        frequency: 70,
      },
      {
        type: "noise_filter",
        startOffset: 0,
        duration: 0.25,
        gain: 0.18,
        filterType: "lowpass",
        frequency: 400,
        q: 0.7,
      },
    ]),
  },
  magic_zap: {
    label: "Magic zap",
    description: "Quick descending sawtooth zap for a spell cast",
    profiles: freezeProfiles([
      {
        type: "oscillator",
        startOffset: 0,
        duration: 0.18,
        gain: 0.2,
        oscillatorType: "sawtooth",
        frequency: 1800,
      },
      {
        type: "noise_filter",
        startOffset: 0,
        duration: 0.22,
        gain: 0.12,
        filterType: "highpass",
        frequency: 2400,
        q: 1,
      },
    ]),
  },
  squelch: {
    label: "Squelch",
    description: "Wet squelch hit with a pitched body, noise smack, click transient, and short wet tail",
    profiles: freezeProfiles([
      {
        type: "oscillator",
        startOffset: 0,
        duration: 0.16,
        gain: 0.7,
        attackTime: 0.005,
        decayCurve: "exponential",
        oscillatorType: "sawtooth",
        frequency: 180,
        sweepEnabled: true,
        frequencyEnd: 55,
        frequencySweep: "exponential",
        reverseBuffer: false,
        muted: false,
        effects: [
          {
            type: "filter",
            filterType: "bandpass",
            frequency: 1400,
            q: 14,
            gain: 0,
            sweepEnabled: true,
            frequencyEnd: 180,
            frequencySweep: "exponential",
          },
          { type: "filter", filterType: "lowpass", frequency: 900, q: 4, gain: 0 },
          { type: "delay", delayTime: 0.045, feedback: 0.22, mix: 0.18 },
        ],
      },
      {
        type: "noise_filter",
        noiseType: "white",
        startOffset: 0,
        duration: 0.045,
        gain: 0.5,
        attackTime: 0.002,
        decayCurve: "exponential",
        filterType: "bandpass",
        frequency: 1200,
        q: 2,
        sweepEnabled: false,
        frequencyEnd: 1200,
        frequencySweep: "exponential",
        reverseBuffer: false,
        muted: false,
        effects: [
          {
            type: "filter",
            filterType: "bandpass",
            frequency: 1400,
            q: 14,
            gain: 0,
            sweepEnabled: true,
            frequencyEnd: 180,
            frequencySweep: "exponential",
          },
          { type: "filter", filterType: "lowpass", frequency: 900, q: 4, gain: 0 },
          { type: "delay", delayTime: 0.045, feedback: 0.22, mix: 0.18 },
        ],
      },
      {
        type: "oscillator",
        startOffset: 0,
        duration: 0.015,
        gain: 0.18,
        attackTime: 0.001,
        decayCurve: "exponential",
        oscillatorType: "square",
        frequency: 700,
        sweepEnabled: true,
        frequencyEnd: 220,
        frequencySweep: "exponential",
        reverseBuffer: false,
        muted: false,
        effects: [
          {
            type: "filter",
            filterType: "bandpass",
            frequency: 1400,
            q: 14,
            gain: 0,
            sweepEnabled: true,
            frequencyEnd: 180,
            frequencySweep: "exponential",
          },
          { type: "filter", filterType: "lowpass", frequency: 900, q: 4, gain: 0 },
        ],
      },
    ]),
  },
  ooze: {
    label: "Ooze",
    description: "Long thick gloop with moving lowpass noise and a descending sub layer",
    profiles: freezeProfiles([
      {
        type: "noise_filter",
        noiseType: "white",
        startOffset: 0,
        duration: 0.22,
        gain: 0.36,
        attackTime: 0.03,
        decayCurve: "exponential",
        filterType: "lowpass",
        frequency: 300,
        q: 12,
        sweepEnabled: true,
        frequencyEnd: 1200,
        frequencySweep: "linear",
        frequencyLfoEnabled: true,
        frequencyLfoRate: 4,
        frequencyLfoDepth: 120,
        reverseBuffer: false,
        muted: false,
        effects: [],
      },
      {
        type: "noise_filter",
        noiseType: "white",
        startOffset: 0.12,
        duration: 1.1,
        gain: 0.3,
        attackTime: 0,
        decayCurve: "exponential",
        filterType: "lowpass",
        frequency: 1200,
        q: 12,
        sweepEnabled: true,
        frequencyEnd: 180,
        frequencySweep: "exponential",
        frequencyLfoEnabled: true,
        frequencyLfoRate: 4,
        frequencyLfoDepth: 180,
        reverseBuffer: false,
        muted: false,
        effects: [],
      },
      {
        type: "oscillator",
        startOffset: 0,
        duration: 0.8,
        gain: 0.15,
        attackTime: 0.02,
        decayCurve: "exponential",
        oscillatorType: "sawtooth",
        frequency: 90,
        sweepEnabled: true,
        frequencyEnd: 40,
        frequencySweep: "exponential",
        reverseBuffer: false,
        muted: false,
        effects: [],
      },
    ]),
  },
  wet_slap: {
    label: "Wet slap",
    description: "Broad wet noise slap with a subtle low body, sticky second hit, and short slapback tail",
    profiles: freezeProfiles([
      {
        type: "noise_filter",
        noiseType: "white",
        startOffset: 0,
        duration: 0.075,
        gain: 0.9,
        attackTime: 0.004,
        decayCurve: "exponential",
        filterType: "highpass",
        frequency: 520,
        q: 1,
        sweepEnabled: false,
        frequencyEnd: 520,
        frequencySweep: "exponential",
        reverseBuffer: false,
        muted: false,
        effects: [
          { type: "filter", filterType: "bandpass", frequency: 1250, q: 0.8, gain: 0 },
          { type: "filter", filterType: "lowpass", frequency: 3200, q: 0.8, gain: 0 },
          { type: "delay", delayTime: 0.026, feedback: 0.16, mix: 0.22 },
        ],
      },
      {
        type: "oscillator",
        startOffset: 0.004,
        duration: 0.09,
        gain: 0.16,
        attackTime: 0.008,
        decayCurve: "exponential",
        oscillatorType: "triangle",
        frequency: 145,
        sweepEnabled: true,
        frequencyEnd: 80,
        frequencySweep: "exponential",
        reverseBuffer: false,
        muted: false,
        effects: [
          { type: "filter", filterType: "lowpass", frequency: 650, q: 1.4, gain: 0 },
          { type: "delay", delayTime: 0.026, feedback: 0.16, mix: 0.18 },
        ],
      },
      {
        type: "noise_filter",
        noiseType: "white",
        startOffset: 0.016,
        duration: 0.085,
        gain: 0.62,
        attackTime: 0.006,
        decayCurve: "exponential",
        filterType: "bandpass",
        frequency: 780,
        q: 1.6,
        sweepEnabled: false,
        frequencyEnd: 780,
        frequencySweep: "exponential",
        reverseBuffer: false,
        muted: false,
        effects: [
          { type: "filter", filterType: "lowpass", frequency: 1800, q: 1, gain: 0 },
          { type: "delay", delayTime: 0.032, feedback: 0.18, mix: 0.28 },
        ],
      },
      {
        type: "noise_filter",
        noiseType: "pink",
        startOffset: 0.025,
        duration: 0.16,
        gain: 0.22,
        attackTime: 0.012,
        decayCurve: "exponential",
        filterType: "lowpass",
        frequency: 1100,
        q: 1.2,
        sweepEnabled: true,
        frequencyEnd: 420,
        frequencySweep: "exponential",
        reverseBuffer: false,
        muted: false,
        effects: [
          { type: "delay", delayTime: 0.034, feedback: 0.12, mix: 0.22 },
        ],
      },
    ]),
  },
  gouging_bite: {
    label: "Gouging bite",
    description: "Descending jaw body with a delayed resonant tearing noise sweep",
    profiles: freezeProfiles([
      {
        type: "oscillator",
        startOffset: 0,
        duration: 0.08,
        gain: 0.4,
        attackTime: 0.003,
        decayCurve: "exponential",
        oscillatorType: "triangle",
        frequency: 200,
        sweepEnabled: true,
        frequencyEnd: 65,
        frequencySweep: "exponential",
        reverseBuffer: false,
        muted: false,
        effects: [],
      },
      {
        type: "noise_filter",
        noiseType: "white",
        startOffset: 0.01,
        duration: 0.17,
        gain: 0.7,
        attackTime: 0.01,
        decayCurve: "exponential",
        filterType: "bandpass",
        frequency: 1500,
        q: 10,
        sweepEnabled: true,
        frequencyEnd: 250,
        frequencySweep: "exponential",
        reverseBuffer: false,
        muted: false,
        effects: [],
      },
    ]),
  },
  door_creak: {
    label: "Door creak",
    description: "Slow groaning hinge for a door open or close",
    profiles: freezeProfiles([
      {
        type: "noise_filter",
        startOffset: 0,
        duration: 0.7,
        gain: 0.25,
        filterType: "bandpass",
        frequency: 240,
        q: 9,
        effects: [
          { type: "distortion", amount: 25, oversample: "4x" },
        ],
      },
      {
        type: "oscillator",
        startOffset: 0.1,
        duration: 0.5,
        gain: 0.12,
        oscillatorType: "sawtooth",
        frequency: 110,
      },
    ]),
  },
  bell: {
    label: "Bell",
    description: "Inharmonic sine stack for a soft bell ring",
    profiles: freezeProfiles([
      {
        type: "periodic_wave",
        startOffset: 0,
        duration: 1.2,
        gain: 0.18,
        frequency: 440,
        harmonics: "bell",
      },
      {
        type: "oscillator",
        startOffset: 0,
        duration: 1.0,
        gain: 0.08,
        oscillatorType: "sine",
        frequency: 880,
      },
    ]),
  },
});

export const listPresetIds = () => Object.keys(PRESETS);
export const getPreset = (id) => PRESETS[id] ?? null;
