import { playProfileSynth } from "@core/profile_synth";

// Slash swing -- short reversed noise sweep matching the 8-frame sword animation.
export const SLASH_SWING_PROFILES = Object.freeze([
  Object.freeze({
    type: "pure_noise",
    noiseType: "brown",
    reverseBuffer: true,
    muted: false,
    startOffset: 0,
    duration: 0.13,
    gain: 0.71,
    effects: Object.freeze([
      Object.freeze({
        type: "reverb",
        duration: 0.13,
        decay: 4.7,
        mix: 1,
      }),
      Object.freeze({
        type: "distortion",
        amount: 183,
        oversample: "4x",
      }),
    ]),
  }),
  Object.freeze({
    type: "pure_noise",
    noiseType: "pink",
    reverseBuffer: true,
    muted: false,
    startOffset: 0.03,
    duration: 0.1,
    gain: 0.59,
    effects: Object.freeze([
      Object.freeze({
        type: "reverb",
        duration: 0.1,
        decay: 4.7,
        mix: 1,
      }),
      Object.freeze({
        type: "distortion",
        amount: 313,
        oversample: "4x",
      }),
    ]),
  }),
  Object.freeze({
    type: "pure_noise",
    noiseType: "white",
    reverseBuffer: true,
    muted: false,
    startOffset: 0.07,
    duration: 0.06,
    gain: 0.59,
    effects: Object.freeze([
      Object.freeze({
        type: "reverb",
        duration: 0.1,
        decay: 4.7,
        mix: 1,
      }),
      Object.freeze({
        type: "distortion",
        amount: 313,
        oversample: "4x",
      }),
    ]),
  }),
]);

// Slash hit -- short wet loud very high flesh-ripping sword contact.
export const SLASH_HIT_PROFILES = Object.freeze([
  Object.freeze({
    type: "noise_filter",
    description: "Very high blade entry that starts the upward rip with a sharp wet edge.",
    noiseType: "pink",
    startOffset: 0,
    duration: 0.055,
    gain: 0.54,
    attackTime: 0.002,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1300,
    q: 2,
    sweepEnabled: true,
    frequencyEnd: 2050,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3800,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Main very high rip bed: loud continuous pink-noise friction, rising quickly through the cut.",
    noiseType: "pink",
    startOffset: 0.014,
    duration: 0.235,
    gain: 0.9,
    attackTime: 0.006,
    decayCurve: "linear",
    filterType: "bandpass",
    frequency: 1050,
    q: 2.35,
    sweepEnabled: true,
    frequencyEnd: 2500,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3900,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.011,
        feedback: 0.13,
        mix: 0.12,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Very bright wet fibrous body underneath the rip, shortened so the whole effect ends near 0.3 seconds.",
    noiseType: "pink",
    startOffset: 0.028,
    duration: 0.22,
    gain: 0.48,
    attackTime: 0.01,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 1550,
    q: 1.3,
    sweepEnabled: true,
    frequencyEnd: 2300,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.016,
        feedback: 0.11,
        mix: 0.12,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "First very bright broad tear: loud fibrous pull instead of a short tick.",
    noiseType: "pink",
    startOffset: 0.038,
    duration: 0.05,
    gain: 0.62,
    attackTime: 0.002,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1280,
    q: 3,
    sweepEnabled: true,
    frequencyEnd: 2550,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 4100,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.009,
        feedback: 0.15,
        mix: 0.13,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Second very bright broad tear: wet pull overlapping the main rip, shifted higher for a sharper tearing read.",
    noiseType: "pink",
    startOffset: 0.082,
    duration: 0.055,
    gain: 0.58,
    attackTime: 0.0025,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1150,
    q: 2.9,
    sweepEnabled: true,
    frequencyEnd: 2250,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.01,
        feedback: 0.14,
        mix: 0.12,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Third very bright broad tear: higher wet mid-rip stretch, compressed for a quick slice.",
    noiseType: "pink",
    startOffset: 0.132,
    duration: 0.065,
    gain: 0.53,
    attackTime: 0.003,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1050,
    q: 2.7,
    sweepEnabled: true,
    frequencyEnd: 1950,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.012,
        feedback: 0.12,
        mix: 0.11,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Fourth very bright broad tear: final rough pull before the short wet tail.",
    noiseType: "pink",
    startOffset: 0.195,
    duration: 0.06,
    gain: 0.43,
    attackTime: 0.0035,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 980,
    q: 2.5,
    sweepEnabled: true,
    frequencyEnd: 1700,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.014,
        feedback: 0.11,
        mix: 0.1,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Short very bright wet drag tail, ending the full sound at about 0.3 seconds.",
    noiseType: "pink",
    startOffset: 0.225,
    duration: 0.075,
    gain: 0.34,
    attackTime: 0.006,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 1500,
    q: 1.1,
    sweepEnabled: true,
    frequencyEnd: 2150,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.02,
        feedback: 0.08,
        mix: 0.1,
      }),
    ]),
  }),
]);

export function playSlashSwing(profiles = SLASH_SWING_PROFILES) {
  playProfileSynth(profiles);
}

export function playSlashWhiff(profiles = SLASH_SWING_PROFILES) {
  playSlashSwing(profiles);
}

export function playSlashHit(profiles = SLASH_HIT_PROFILES) {
  playProfileSynth(profiles);
}
