import { playProfileSynth } from "@core/profile_synth";

export const HAMMER_HIT_PROFILES = Object.freeze([
  Object.freeze({
    type: "oscillator",
    description: "Deep compact hammer body: main blunt force, low and crushing.",
    startOffset: 0,
    duration: 0.14,
    gain: 0.56,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 78,
    sweepEnabled: true,
    frequencyEnd: 34,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 320,
        q: 0.9,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Heavy compression slap: dense lowpass pink noise that sells material being crushed under the metal hammer.",
    noiseType: "pink",
    startOffset: 0,
    duration: 0.13,
    gain: 0.9,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 500,
    q: 1.5,
    sweepEnabled: true,
    frequencyEnd: 210,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 9,
        oversample: "2x",
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.022,
        feedback: 0.1,
        mix: 0.1,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Crashing debris burst: broad noisy impact layer that makes the hit feel larger, like armor, stone, or wreckage collapsing around the hammer strike.",
    noiseType: "white",
    startOffset: 0.012,
    duration: 0.18,
    gain: 0.34,
    attackTime: 0.002,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 950,
    q: 1.4,
    sweepEnabled: true,
    frequencyEnd: 420,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 10,
        oversample: "2x",
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.028,
        feedback: 0.22,
        mix: 0.18,
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2600,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Low crash wash: darker rubble-like crash underneath the metal hit, adding scale and devastation without becoming a bright bone crack.",
    noiseType: "pink",
    startOffset: 0.028,
    duration: 0.24,
    gain: 0.38,
    attackTime: 0.006,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 460,
    q: 1.8,
    sweepEnabled: true,
    frequencyEnd: 160,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 12,
        oversample: "2x",
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.04,
        feedback: 0.18,
        mix: 0.16,
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1200,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Muted metal strike: lower clank so the hammer reads as metal without sounding brittle.",
    noiseType: "white",
    startOffset: 0.005,
    duration: 0.024,
    gain: 0.28,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1450,
    q: 3.1,
    sweepEnabled: true,
    frequencyEnd: 820,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 5,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2600,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "oscillator",
    description: "Metal ping fundamental: clear metallic tone from the hammer head, delayed slightly after the crush.",
    startOffset: 0.012,
    duration: 0.22,
    gain: 0.12,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "sine",
    frequency: 1320,
    sweepEnabled: true,
    frequencyEnd: 1180,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "bandpass",
        frequency: 1320,
        q: 4.2,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.035,
        feedback: 0.34,
        mix: 0.26,
      }),
    ]),
  }),
  Object.freeze({
    type: "oscillator",
    description: "Metal ping overtone: quieter higher harmonic that makes the ping feel like metal instead of a simple beep.",
    startOffset: 0.016,
    duration: 0.16,
    gain: 0.045,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "sine",
    frequency: 2640,
    sweepEnabled: true,
    frequencyEnd: 2380,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "bandpass",
        frequency: 2600,
        q: 4.6,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.028,
        feedback: 0.26,
        mix: 0.2,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "First low splinter crack: chunky fracture detail from material giving way under the hammer.",
    noiseType: "white",
    startOffset: 0.024,
    duration: 0.055,
    gain: 0.38,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 820,
    q: 3.2,
    sweepEnabled: true,
    frequencyEnd: 360,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 11,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1800,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Crushing splinter bed: louder lower-mid tearing and grinding that sounds like material collapsing under the hammer.",
    noiseType: "pink",
    startOffset: 0.035,
    duration: 0.26,
    gain: 0.56,
    attackTime: 0.008,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 320,
    q: 2.5,
    sweepEnabled: true,
    frequencyEnd: 135,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 14,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1100,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.018,
        feedback: 0.12,
        mix: 0.11,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Second low splinter: delayed chunky split after the main contact, adding destruction without brittle highs.",
    noiseType: "white",
    startOffset: 0.068,
    duration: 0.07,
    gain: 0.3,
    attackTime: 0.002,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 640,
    q: 2.9,
    sweepEnabled: true,
    frequencyEnd: 270,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 9,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1400,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.013,
        feedback: 0.08,
        mix: 0.08,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Third crushing split: lower late fracture that makes the hit feel like it keeps breaking inward after impact.",
    noiseType: "white",
    startOffset: 0.112,
    duration: 0.075,
    gain: 0.24,
    attackTime: 0.0025,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 520,
    q: 2.6,
    sweepEnabled: true,
    frequencyEnd: 230,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 8,
        oversample: "2x",
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1200,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Metallic crushed grit: mid-high rough scrape mixed with the ping so the hammer feels metal-on-crushed-material.",
    noiseType: "white",
    startOffset: 0.045,
    duration: 0.12,
    gain: 0.16,
    attackTime: 0.004,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1700,
    q: 2.4,
    sweepEnabled: true,
    frequencyEnd: 900,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 8,
        oversample: "2x",
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.018,
        feedback: 0.16,
        mix: 0.12,
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3100,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "oscillator",
    description: "Restrained lower metal resonance: supports the ping with a quieter low ring from the hammer head.",
    startOffset: 0.022,
    duration: 0.14,
    gain: 0.055,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "sine",
    frequency: 720,
    sweepEnabled: true,
    frequencyEnd: 520,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "bandpass",
        frequency: 720,
        q: 2.6,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.026,
        feedback: 0.22,
        mix: 0.18,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Deep rubble tail: longer low gritty decay, like crushed material settling after the hammer blow.",
    noiseType: "pink",
    startOffset: 0.115,
    duration: 0.24,
    gain: 0.32,
    attackTime: 0.014,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 400,
    q: 1.3,
    sweepEnabled: true,
    frequencyEnd: 150,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "distortion",
        amount: 5,
        oversample: "2x",
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.038,
        feedback: 0.11,
        mix: 0.12,
      }),
    ]),
  }),
]);

export const playHammerHit = (profiles = HAMMER_HIT_PROFILES) => {
  playProfileSynth(profiles);
};
