import { playProfileSynth } from "@core/profile_synth";

export const GREATSWORD_HIT_PROFILES = Object.freeze([
  Object.freeze({
    type: "noise_filter",
    description: "Heavy blade entry: slightly brighter than the prior greatsword version while still feeling broad and heavy.",
    noiseType: "pink",
    startOffset: 0,
    duration: 0.105,
    gain: 0.58,
    attackTime: 0.004,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 640,
    q: 2.1,
    sweepEnabled: true,
    frequencyEnd: 1180,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2500,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.012,
        feedback: 0.08,
        mix: 0.08,
      }),
    ]),
  }),
  Object.freeze({
    type: "oscillator",
    description: "Subtle deep impact weight: unchanged low body so the greatsword still feels heavy, not thin.",
    startOffset: 0.006,
    duration: 0.095,
    gain: 0.18,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 120,
    sweepEnabled: true,
    frequencyEnd: 58,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 420,
        q: 0.9,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Main greatsword flesh rip bed: raised slightly in pitch, still wide and slower than the one-handed sword rip.",
    noiseType: "pink",
    startOffset: 0.028,
    duration: 0.38,
    gain: 0.76,
    attackTime: 0.012,
    decayCurve: "linear",
    filterType: "bandpass",
    frequency: 460,
    q: 2.5,
    sweepEnabled: true,
    frequencyEnd: 1360,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2700,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.016,
        feedback: 0.14,
        mix: 0.13,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Wet gore body: slightly brighter thick lowpass pink noise that keeps the slice organic and devastating.",
    noiseType: "pink",
    startOffset: 0.05,
    duration: 0.36,
    gain: 0.42,
    attackTime: 0.018,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 820,
    q: 1.45,
    sweepEnabled: true,
    frequencyEnd: 1380,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.024,
        feedback: 0.13,
        mix: 0.14,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "First broad tearing pull: brighter fibrous rip as the greatsword catches and opens flesh.",
    noiseType: "pink",
    startOffset: 0.07,
    duration: 0.085,
    gain: 0.56,
    attackTime: 0.003,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 600,
    q: 3,
    sweepEnabled: true,
    frequencyEnd: 1500,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2800,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.012,
        feedback: 0.16,
        mix: 0.14,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Second broad tearing pull: overlapping wet drag, raised slightly so the rip has a sharper greatsword edge.",
    noiseType: "pink",
    startOffset: 0.14,
    duration: 0.105,
    gain: 0.5,
    attackTime: 0.004,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 540,
    q: 2.9,
    sweepEnabled: true,
    frequencyEnd: 1260,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.014,
        feedback: 0.15,
        mix: 0.13,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Third heavy tearing pull: higher mid-rip stretch while preserving the larger blade dragging through dense material.",
    noiseType: "pink",
    startOffset: 0.23,
    duration: 0.115,
    gain: 0.42,
    attackTime: 0.005,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 460,
    q: 2.7,
    sweepEnabled: true,
    frequencyEnd: 1060,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.017,
        feedback: 0.12,
        mix: 0.12,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Bright steel/flesh edge: slightly stronger high-mid tearing detail so the hit reads clearly as a sword.",
    noiseType: "white",
    startOffset: 0.055,
    duration: 0.12,
    gain: 0.2,
    attackTime: 0.002,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1750,
    q: 2.6,
    sweepEnabled: true,
    frequencyEnd: 2900,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 4200,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Devastating wet finish: slightly brighter gore smear after the greatsword finishes the cut.",
    noiseType: "pink",
    startOffset: 0.32,
    duration: 0.18,
    gain: 0.28,
    attackTime: 0.012,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 660,
    q: 1.25,
    sweepEnabled: true,
    frequencyEnd: 980,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.032,
        feedback: 0.1,
        mix: 0.12,
      }),
    ]),
  }),
]);

export const playGreatswordHit = (profiles = GREATSWORD_HIT_PROFILES) => {
  playProfileSynth(profiles);
};
