import { playProfileSynth } from "@core/profile_synth";

export const MACE_HIT_PROFILES = Object.freeze([
  Object.freeze({
    type: "oscillator",
    description: "Main mace thud: blunt low body that gives the weapon weight without making it as huge as a greathammer.",
    startOffset: 0,
    duration: 0.13,
    gain: 0.58,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 76,
    sweepEnabled: true,
    frequencyEnd: 34,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 300,
        q: 0.9,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "oscillator",
    description: "Hard upper thud: short low-mid punch from the mace head striking hard material.",
    startOffset: 0.004,
    duration: 0.085,
    gain: 0.28,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 145,
    sweepEnabled: true,
    frequencyEnd: 72,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 520,
        q: 1,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Dense blunt contact: heavy lowpass impact noise, like a metal mace compressing armor, bone, or wood.",
    noiseType: "pink",
    startOffset: 0,
    duration: 0.115,
    gain: 0.84,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 480,
    q: 1.45,
    sweepEnabled: true,
    frequencyEnd: 190,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 10, oversample: "2x" }),
      Object.freeze({
        type: "delay",
        delayTime: 0.022,
        feedback: 0.09,
        mix: 0.09,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Compact crash burst: short debris-like noise layer that makes the mace hit feel destructive without becoming as wide as a greathammer.",
    noiseType: "white",
    startOffset: 0.008,
    duration: 0.16,
    gain: 0.34,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 740,
    q: 1.25,
    sweepEnabled: true,
    frequencyEnd: 260,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 12, oversample: "2x" }),
      Object.freeze({
        type: "delay",
        delayTime: 0.028,
        feedback: 0.2,
        mix: 0.16,
      }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2100,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Hard mace-face smack: short mid-low strike noise from metal studs or flanges biting into the target.",
    noiseType: "white",
    startOffset: 0.006,
    duration: 0.04,
    gain: 0.32,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 820,
    q: 2.4,
    sweepEnabled: true,
    frequencyEnd: 360,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 9, oversample: "2x" }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1700,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Primary splinter break: chunky fracture immediately after the mace impact, like wood, shield, or bone giving way.",
    noiseType: "white",
    startOffset: 0.022,
    duration: 0.065,
    gain: 0.4,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 720,
    q: 3.1,
    sweepEnabled: true,
    frequencyEnd: 300,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 12, oversample: "2x" }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1500,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "High splinter shard one: slightly higher-pitched brittle crackle layered on top of the chunky break.",
    noiseType: "white",
    startOffset: 0.034,
    duration: 0.045,
    gain: 0.18,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1850,
    q: 3.8,
    sweepEnabled: true,
    frequencyEnd: 980,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 7, oversample: "2x" }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3400,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.012,
        feedback: 0.08,
        mix: 0.08,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "High splinter shard two: delayed bright fragment snap so the mace hit has a little extra brittle detail.",
    noiseType: "white",
    startOffset: 0.082,
    duration: 0.052,
    gain: 0.14,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1550,
    q: 3.4,
    sweepEnabled: true,
    frequencyEnd: 820,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 6, oversample: "2x" }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3000,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Secondary splinter crunch: delayed lower break so the target sounds like it keeps cracking after the mace lands.",
    noiseType: "white",
    startOffset: 0.07,
    duration: 0.075,
    gain: 0.3,
    attackTime: 0.002,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 540,
    q: 2.8,
    sweepEnabled: true,
    frequencyEnd: 230,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 9, oversample: "2x" }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1200,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.014,
        feedback: 0.08,
        mix: 0.08,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Crushing grind bed: lower-mid grinding collapse under the impact, selling blunt trauma rather than a clean metal ring.",
    noiseType: "pink",
    startOffset: 0.035,
    duration: 0.24,
    gain: 0.52,
    attackTime: 0.008,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 290,
    q: 2.5,
    sweepEnabled: true,
    frequencyEnd: 120,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 14, oversample: "2x" }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 900,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.02,
        feedback: 0.11,
        mix: 0.1,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Small higher splinter shards: restrained bright crackle from small fragments breaking away after the mace strike.",
    noiseType: "white",
    startOffset: 0.045,
    duration: 0.07,
    gain: 0.15,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1450,
    q: 3.4,
    sweepEnabled: true,
    frequencyEnd: 760,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 7, oversample: "2x" }),
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2800,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Short rubble tail: low gritty decay from crushed material settling after the mace blow.",
    noiseType: "pink",
    startOffset: 0.13,
    duration: 0.18,
    gain: 0.24,
    attackTime: 0.014,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 360,
    q: 1.3,
    sweepEnabled: true,
    frequencyEnd: 140,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({ type: "distortion", amount: 5, oversample: "2x" }),
      Object.freeze({
        type: "delay",
        delayTime: 0.036,
        feedback: 0.1,
        mix: 0.11,
      }),
    ]),
  }),
]);

export const playMaceHit = (profiles = MACE_HIT_PROFILES) => {
  playProfileSynth(profiles);
};
