// Coin pouch HUD widget. Replaces the plain "x N" coin counter with a
// drawstring leather pouch that visibly grows from a flat, lopsided
// "deflated" silhouette (0 coins) to a tall, plump, perfectly symmetric
// silhouette (10+ coins, overflowing).
//
// The five fullness states are baked into a static PNG sprite sheet on
// disk (src/assets/ui/coin_pouch/sprite.png, 240x48 = 5 frames of 48x48)
// generated by scripts/generate_coin_pouch_sprite.js. At runtime we just
// blit the matching frame for the current coin count — no canvas
// gradients, no procedural curves, no runtime sprite-sheet generation.
//
//   bucket 0:  0 coins      flat, narrow, very lopsided, no coins inside
//   bucket 1:  1–3 coins    slightly fuller, still floppy, 1 coin
//   bucket 2:  4–6 coins    medium, mild lean, 3 coins peeking
//   bucket 3:  7–9 coins    nearly full, almost symmetric, 4 coins
//   bucket 4: 10+ coins     biggest, perfectly symmetric, 5 coins inside
//                           + overflow coins floating above the mouth
//
// Because goblins can steal coins back, the displayed bucket is always a
// live function of the current count — losing coins drops the bag's
// silhouette back to the matching smaller bucket on the next frame
// without any extra event plumbing.
//
// `triggerCoinDropAnim` queues a small "coin falling into pouch" cue that
// `drawCoinPouch` consumes each frame, so picking up a coin reads as a
// physical drop into the bag rather than a silent number change. The
// drop animation is still drawn live on top of the static sprite — only
// the bag itself is the static asset.

const FRAME_SIZE = 48;
const DROP_ANIM_FRAMES = 18;

// Win-threshold sparkle config. Sparkles fire only when the bag is at
// bucket 4 (10+ coins) so the player gets a clear "you have enough to
// climb the ladder!" visual cue. Each twinkle pulses 0 → peak → 0 over
// its randomized lifespan; we keep up to ~`SPARKLE_TARGET_COUNT` alive
// at once and spawn new ones probabilistically every frame so the
// cadence reads organic rather than metronomic.
const SPARKLE_LIFE_MIN = 22;
const SPARKLE_LIFE_MAX = 48;
const SPARKLE_TARGET_COUNT = 4;
const SPARKLE_SPAWN_CHANCE = 0.08;
const SPARKLE_PEAK_RADIUS_FRAC_MIN = 0.06;
const SPARKLE_PEAK_RADIUS_FRAC_MAX = 0.13;
const SPARKLE_SLOT_JITTER = 0.06;

// Where sparkles are allowed to appear, expressed as fractions of the
// widget size (0..1). Slots were derived directly from the bucket-4
// sprite by scanning for warm-gold pixel clusters — see the diagnostic
// in the buildSheet docs. There are three coin clusters in the frame:
//   - overflow pile at the top of the bag (y ≈ 0.15..0.30, x ≈ 0.30..0.65)
//   - drawstring coin-tip cluster on the bag body (y ≈ 0.55..0.70)
//   - spilled coin sitting on the floor (y ≈ 0.78..0.88, x ≈ 0.78..0.92)
// `weight` biases the per-frame slot pick so the visually busiest area
// (the overflow pile) gets the most twinkles without starving the other
// clusters entirely. The per-spawn jitter softens the discrete slots
// into a continuous spawn cloud.
const SPARKLE_SLOTS = Object.freeze([
  // Overflow pile (top of bag) — 6 slots covering the spread.
  { x: 0.34, y: 0.18, weight: 1.2 },
  { x: 0.46, y: 0.14, weight: 1.4 },
  { x: 0.58, y: 0.14, weight: 1.4 },
  { x: 0.66, y: 0.20, weight: 1.2 },
  { x: 0.42, y: 0.26, weight: 1.0 },
  { x: 0.56, y: 0.24, weight: 1.0 },
  // Coin-tip cluster sitting on the bag body around the cinch.
  { x: 0.46, y: 0.65, weight: 0.8 },
  { x: 0.62, y: 0.62, weight: 0.8 },
  { x: 0.74, y: 0.66, weight: 0.7 },
  // Spilled coin on the floor.
  { x: 0.84, y: 0.83, weight: 0.9 },
  { x: 0.90, y: 0.83, weight: 0.7 },
]);

const SPARKLE_TOTAL_WEIGHT = SPARKLE_SLOTS.reduce((sum, s) => sum + s.weight, 0);

// Pick a slot weighted by SPARKLE_SLOTS[i].weight. Plain Math.random()
// uniform-pick would give the spilled coin the same spawn rate as the
// big overflow pile, which doesn't read right.
const pickSparkleSlot = () => {
  let r = Math.random() * SPARKLE_TOTAL_WEIGHT;
  for (const slot of SPARKLE_SLOTS) {
    r -= slot.weight;
    if (r <= 0) return slot;
  }
  return SPARKLE_SLOTS[SPARKLE_SLOTS.length - 1];
};

// Per-bucket relative Y of the bag mouth (where the dropped coin should
// "land") as a fraction of FRAME_SIZE. Auto-emitted by
// scripts/generate_coin_pouch_sprite.js — it scans each downsampled
// frame for the top-most opaque row and offsets a few pixels lower so
// the coin reads as falling INTO the bag, not landing on the drawstring
// tips. Re-run the generator and paste the new array here whenever the
// source artwork or crop layout changes.
const MUZZLE_TOP_BY_BUCKET = Object.freeze([0.438, 0.396, 0.292, 0.292, 0.146]);

// Five buckets across 0..10+ coins. Bucket 0 is the special "totally
// empty" state and bucket 4 is the special "overflow" state; the three
// middle buckets are evenly-spaced fill levels in between.
const bucketForCoinCount = (coinCount) => {
  if (coinCount <= 0) return 0;
  if (coinCount <= 3) return 1;
  if (coinCount <= 6) return 2;
  if (coinCount <= 9) return 3;
  return 4;
};

// Drop animation: small coin disc falling from the top of the widget
// into the bag's mouth. `mouthYNorm` floats with the current bucket so
// the coin lands at the right height regardless of how full the bag is.
const drawDropAnims = (player, ctx, x, y, outerSize, mouthYNorm) => {
  const drops = player?.coinPouchDrops;
  if (!Array.isArray(drops) || drops.length === 0) return;
  const cx = x + outerSize * 0.5;
  const startY = y + 1;
  const endY = y + outerSize * mouthYNorm + 2;
  const baseR = outerSize * 0.07;
  for (const drop of drops) {
    const t = Math.min(1, drop.frame / DROP_ANIM_FRAMES);
    const yPos = startY + (endY - startY) * t;
    const alpha = t < 0.78 ? 1 : Math.max(0, 1 - (t - 0.78) / 0.22);
    ctx.save();
    ctx.globalAlpha = alpha;
    ctx.fillStyle = "#ffcf32";
    ctx.beginPath();
    ctx.ellipse(cx, yPos, baseR, baseR * 0.85, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.strokeStyle = "#5a3e10";
    ctx.lineWidth = 0.7;
    ctx.stroke();
    ctx.fillStyle = "#fff5b6";
    ctx.beginPath();
    ctx.ellipse(cx - baseR * 0.3, yPos - baseR * 0.35, baseR * 0.45, baseR * 0.3, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.restore();
  }
};

// Win-threshold sparkles. Drawn live each frame on top of the static
// bucket-4 sprite (NOT baked into the PNG) so each pouch on screen
// twinkles independently and the effect can pause / resume cleanly with
// the rest of the UI. Each sparkle is a 4-point star whose arm length
// pulses 0 → peak → 0 across its randomized lifespan; a tiny secondary
// "x" set of arms at half-size sells the classic Cinderella twinkle.
//
// `rotation` is a per-instance random tilt applied to the entire star so
// adjacent sparkles don't all stamp identical axis-aligned crosses.
const drawSparkleStar = (ctx, cx, cy, r, rotation) => {
  if (r <= 0.4) return;

  ctx.save();
  ctx.translate(cx, cy);
  ctx.rotate(rotation);
  ctx.fillStyle = "#fff7c8";
  // Vertical and horizontal arms of the main 4-point star.
  ctx.fillRect(-0.5, -r, 1, r * 2);
  ctx.fillRect(-r, -0.5, r * 2, 1);

  // Smaller diagonal "x" arms once the sparkle is past the smallest size,
  // for an 8-point look at the peak.
  if (r > 1.2) {
    const dr = r * 0.55;
    ctx.save();
    ctx.rotate(Math.PI / 4);
    ctx.fillRect(-0.5, -dr, 1, dr * 2);
    ctx.fillRect(-dr, -0.5, dr * 2, 1);
    ctx.restore();
  }

  // Bright white core dot at the largest sparkle sizes.
  if (r > 1.6) {
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(-1, -1, 2, 2);
  }
  ctx.restore();
};

const drawSparkles = (player, ctx, x, y, outerSize) => {
  const sparkles = player?.coinPouchSparkles;
  if (!Array.isArray(sparkles) || sparkles.length === 0) return;
  for (const sp of sparkles) {
    const t = sp.age / sp.life;
    if (t < 0 || t > 1) continue;
    const sizeT = Math.sin(t * Math.PI);
    const r = outerSize * sp.peakRFrac * sizeT;
    if (r <= 0.4) continue;
    const cx = x + outerSize * sp.x;
    const cy = y + outerSize * sp.y;
    drawSparkleStar(ctx, cx, cy, r, sp.rotation);
  }
};

// Fire-and-forget: schedule a "coin falls into pouch" animation for the
// next few HUD frames. Call this every time the coin counter goes up so
// the player gets a clear visual ack on pickup.
export const triggerCoinDropAnim = (player) => {
  if (!player) return;
  if (!Array.isArray(player.coinPouchDrops)) player.coinPouchDrops = [];
  player.coinPouchDrops.push({ frame: 0 });
};

// Tick existing drop anims forward and discard finished ones. Also runs
// the win-threshold sparkle animation: tick every active sparkle, drop
// dead ones, and probabilistically spawn new ones whenever the player is
// at bucket 4 (10+ coins). Called once per HUD frame from `room.drawHUD`,
// before `drawCoinPouch`, so even a paused render loop won't accumulate
// stale animations on resume.
export const updateCoinPouchAnims = (player, coinCount = 0) => {
  if (!player) return;

  const drops = Array.isArray(player.coinPouchDrops) ? player.coinPouchDrops : [];
  if (drops.length > 0) {
    for (const drop of drops) drop.frame++;
    player.coinPouchDrops = drops.filter(d => d.frame < DROP_ANIM_FRAMES);
  }

  if (!Array.isArray(player.coinPouchSparkles)) player.coinPouchSparkles = [];
  const sparkles = player.coinPouchSparkles;
  if (sparkles.length > 0) {
    for (const sp of sparkles) sp.age++;
    player.coinPouchSparkles = sparkles.filter(sp => sp.age < sp.life);
  }

  // Sparkles only fire while the bag is at the win threshold. If the
  // player drops below 10 coins (e.g. a goblin steals one), existing
  // sparkles still finish their pulse but no new ones spawn.
  if (bucketForCoinCount(coinCount) !== 4) return;

  if (player.coinPouchSparkles.length < SPARKLE_TARGET_COUNT
      && Math.random() < SPARKLE_SPAWN_CHANCE) {
    const slot = pickSparkleSlot();
    const lifeRange = SPARKLE_LIFE_MAX - SPARKLE_LIFE_MIN;
    const peakRange = SPARKLE_PEAK_RADIUS_FRAC_MAX - SPARKLE_PEAK_RADIUS_FRAC_MIN;
    player.coinPouchSparkles.push({
      x: slot.x + (Math.random() - 0.5) * SPARKLE_SLOT_JITTER,
      y: slot.y + (Math.random() - 0.5) * SPARKLE_SLOT_JITTER,
      age: 0,
      life: SPARKLE_LIFE_MIN + Math.floor(Math.random() * lifeRange),
      peakRFrac: SPARKLE_PEAK_RADIUS_FRAC_MIN + Math.random() * peakRange,
      rotation: Math.random() * Math.PI / 2,
    });
  }
};

// Draws the pouch widget centered horizontally inside an `outerSize`-by-
// `outerSize` square anchored at (x, y). Returns the same outerSize so
// callers can reuse it for layout math without redoing the calculation.
//
// `sprite` is the preloaded sprite sheet from gameState.sprites.coinPouch
// — passed by the caller (room.drawHUD) so this module stays pure (no
// gameState reach-through). If the sprite isn't loaded yet (e.g. boot
// race), the widget no-ops gracefully and the drop animation still runs
// once it loads.
export const drawCoinPouch = (ctx, x, y, coinCount, outerSize, player, sprite) => {
  const bucket = bucketForCoinCount(coinCount);

  if (sprite && sprite.complete && sprite.naturalWidth > 0) {
    ctx.drawImage(
      sprite,
      bucket * FRAME_SIZE, 0, FRAME_SIZE, FRAME_SIZE,
      x, y, outerSize, outerSize,
    );
  }

  drawDropAnims(player, ctx, x, y, outerSize, MUZZLE_TOP_BY_BUCKET[bucket]);
  if (bucket === 4) drawSparkles(player, ctx, x, y, outerSize);
  return outerSize;
};
