import { playProfileSynth } from "@core/profile_synth";

export const WAND_HIT_PROFILES = Object.freeze([
  Object.freeze({
    type: "oscillator",
    description: "Subtle deeper thud: low support under the slap so the hit has body without becoming a hammer impact.",
    startOffset: 0,
    duration: 0.09,
    gain: 0.16,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 105,
    sweepEnabled: true,
    frequencyEnd: 58,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 340,
        q: 0.85,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "oscillator",
    description: "Soft ham body: rounded low-mid contact so the smack feels fleshy and padded rather than hard.",
    startOffset: 0,
    duration: 0.075,
    gain: 0.24,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 165,
    sweepEnabled: true,
    frequencyEnd: 82,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 520,
        q: 0.9,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Main wet ham slap: thick lowpass pink noise, like damp flesh flattening against a soft surface.",
    noiseType: "pink",
    startOffset: 0,
    duration: 0.095,
    gain: 0.58,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 620,
    q: 1.9,
    sweepEnabled: true,
    frequencyEnd: 260,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.018,
        feedback: 0.11,
        mix: 0.12,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Leather couch slap: low-mid bandpass smack that adds a dull leathery pop underneath the wet flesh layer.",
    noiseType: "pink",
    startOffset: 0.006,
    duration: 0.072,
    gain: 0.36,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 430,
    q: 2.8,
    sweepEnabled: true,
    frequencyEnd: 210,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1100,
        q: 0.8,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.014,
        feedback: 0.09,
        mix: 0.1,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Primary wand wood clock: dry wooden shaft knock layered on top of the wet smack.",
    noiseType: "white",
    startOffset: 0.004,
    duration: 0.032,
    gain: 0.25,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1150,
    q: 4.6,
    sweepEnabled: true,
    frequencyEnd: 620,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2400,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Secondary wood clock: lower delayed knock so the wand still reads as a small wooden object after the wet contact.",
    noiseType: "white",
    startOffset: 0.034,
    duration: 0.03,
    gain: 0.14,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 760,
    q: 4,
    sweepEnabled: true,
    frequencyEnd: 420,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1800,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Sticky wet front edge: small brighter splat at impact so it reads wet instead of just muffled.",
    noiseType: "white",
    startOffset: 0.003,
    duration: 0.026,
    gain: 0.14,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 980,
    q: 2.5,
    sweepEnabled: true,
    frequencyEnd: 520,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1800,
        q: 0.8,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Damp cushion bloom: soft lowpass body after the smack, like the leather surface absorbing the hit.",
    noiseType: "pink",
    startOffset: 0.022,
    duration: 0.13,
    gain: 0.22,
    attackTime: 0.012,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 480,
    q: 1.4,
    sweepEnabled: true,
    frequencyEnd: 190,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.026,
        feedback: 0.08,
        mix: 0.09,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Tiny sticky rebound: delayed wet tack sound as the ham pulls away from the leather.",
    noiseType: "pink",
    startOffset: 0.058,
    duration: 0.045,
    gain: 0.14,
    attackTime: 0.002,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 520,
    q: 2.2,
    sweepEnabled: true,
    frequencyEnd: 300,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.015,
        feedback: 0.08,
        mix: 0.08,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Short damp tail: muffled wet/leather decay so the slap feels soft and absorbed.",
    noiseType: "pink",
    startOffset: 0.085,
    duration: 0.12,
    gain: 0.085,
    attackTime: 0.014,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 360,
    q: 1.15,
    sweepEnabled: true,
    frequencyEnd: 150,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([]),
  }),
]);

export const playWandHit = (profiles = WAND_HIT_PROFILES) => {
  playProfileSynth(profiles);
};
