import { playProfileSynth } from "@core/profile_synth";

export const POLEARM_HIT_PROFILES = Object.freeze([
  Object.freeze({
    type: "noise_filter",
    description: "Very focused spear-point entry: high-Q thrust edge with sharp bite at the start.",
    noiseType: "white",
    startOffset: 0,
    duration: 0.045,
    gain: 0.5,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 2150,
    q: 5.4,
    sweepEnabled: true,
    frequencyEnd: 1150,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3900,
        q: 1.2,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Wet puncture bite: focused slick flesh contact right after the spear point lands.",
    noiseType: "pink",
    startOffset: 0.006,
    duration: 0.072,
    gain: 0.46,
    attackTime: 0.002,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 1050,
    q: 2.35,
    sweepEnabled: true,
    frequencyEnd: 520,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.014,
        feedback: 0.09,
        mix: 0.09,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Main varied gouging spear drag: very focused scraping/gouging texture with a higher Q than the wet body layers.",
    noiseType: "pink",
    startOffset: 0.022,
    duration: 0.24,
    gain: 0.72,
    attackTime: 0.006,
    decayCurve: "linear",
    filterType: "bandpass",
    frequency: 650,
    q: 5.2,
    sweepEnabled: true,
    frequencyEnd: 1550,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2900,
        q: 1.35,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.012,
        feedback: 0.15,
        mix: 0.13,
      }),
      Object.freeze({
        type: "distortion",
        amount: 5,
        oversample: "2x",
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Wet gouge body: moderate Q so the body stays wet and broad under the sharper scraping layers.",
    noiseType: "pink",
    startOffset: 0.032,
    duration: 0.215,
    gain: 0.4,
    attackTime: 0.01,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 900,
    q: 2.35,
    sweepEnabled: true,
    frequencyEnd: 1350,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.02,
        feedback: 0.12,
        mix: 0.12,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "First hard gouging rip: highest-Q fiber pull, giving the first tear a sharp resonant edge.",
    noiseType: "pink",
    startOffset: 0.052,
    duration: 0.07,
    gain: 0.54,
    attackTime: 0.002,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 900,
    q: 5.85,
    sweepEnabled: true,
    frequencyEnd: 1850,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3300,
        q: 1.25,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.01,
        feedback: 0.15,
        mix: 0.13,
      }),
      Object.freeze({
        type: "distortion",
        amount: 4,
        oversample: "2x",
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Second hard gouging rip: different high Q from the first pull so the tear has a different resonant shape.",
    noiseType: "pink",
    startOffset: 0.102,
    duration: 0.08,
    gain: 0.46,
    attackTime: 0.003,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 760,
    q: 4.65,
    sweepEnabled: true,
    frequencyEnd: 1620,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.012,
        feedback: 0.14,
        mix: 0.12,
      }),
      Object.freeze({
        type: "distortion",
        amount: 4,
        oversample: "2x",
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Third gouging scrape: rougher late drag with a lower Q than the first tear but still more focused than the body.",
    noiseType: "pink",
    startOffset: 0.155,
    duration: 0.075,
    gain: 0.34,
    attackTime: 0.004,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 640,
    q: 4.25,
    sweepEnabled: true,
    frequencyEnd: 1280,
    frequencySweep: "linear",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.015,
        feedback: 0.11,
        mix: 0.1,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Spear shaft scrape: very focused dry scrape so the shaft detail cuts through the wet gouge.",
    noiseType: "white",
    startOffset: 0.065,
    duration: 0.14,
    gain: 0.18,
    attackTime: 0.003,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1700,
    q: 4.45,
    sweepEnabled: true,
    frequencyEnd: 920,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 3400,
        q: 1.25,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "oscillator",
    description: "Subtle body pressure: unchanged low-mid weight so the higher Q layers do not make the hit too thin.",
    startOffset: 0.018,
    duration: 0.07,
    gain: 0.1,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 180,
    sweepEnabled: true,
    frequencyEnd: 88,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 460,
        q: 1.1,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Short wet exit smear: focused wet decay after the gouging rip.",
    noiseType: "pink",
    startOffset: 0.19,
    duration: 0.105,
    gain: 0.22,
    attackTime: 0.01,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 760,
    q: 2.05,
    sweepEnabled: true,
    frequencyEnd: 440,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.028,
        feedback: 0.08,
        mix: 0.09,
      }),
    ]),
  }),
]);

export const playPolearmHit = (profiles = POLEARM_HIT_PROFILES) => {
  playProfileSynth(profiles);
};
