import { playProfileSynth } from "@core/profile_synth";

export const STAFF_HIT_PROFILES = Object.freeze([
  Object.freeze({
    type: "oscillator",
    description: "Supportive body thud: blunt impact underneath the wood sound, reduced slightly so the clocking layers stand out.",
    startOffset: 0,
    duration: 0.105,
    gain: 0.34,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 120,
    sweepEnabled: true,
    frequencyEnd: 62,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 360,
        q: 1,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Dry wooden body contact: lowpass pink noise for physical impact, kept dry and woody rather than heavy.",
    noiseType: "pink",
    startOffset: 0,
    duration: 0.07,
    gain: 0.46,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "lowpass",
    frequency: 680,
    q: 1.75,
    sweepEnabled: true,
    frequencyEnd: 340,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.014,
        feedback: 0.07,
        mix: 0.07,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Primary wood clock: loud dry wooden knock from the shaft, the main identity of the staff hit.",
    noiseType: "white",
    startOffset: 0.004,
    duration: 0.05,
    gain: 0.6,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 820,
    q: 5.6,
    sweepEnabled: true,
    frequencyEnd: 430,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1900,
        q: 1.1,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Hollow clonk layer: lower wooden knock that makes the staff sound like a solid pole instead of a thin stick.",
    noiseType: "pink",
    startOffset: 0.01,
    duration: 0.06,
    gain: 0.36,
    attackTime: 0.0015,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 520,
    q: 4.8,
    sweepEnabled: true,
    frequencyEnd: 310,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.018,
        feedback: 0.11,
        mix: 0.1,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Hard dry clack: higher wooden edge detail, like the staff striking with the hard outside grain.",
    noiseType: "white",
    startOffset: 0.014,
    duration: 0.034,
    gain: 0.28,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 1280,
    q: 5.4,
    sweepEnabled: true,
    frequencyEnd: 720,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 2400,
        q: 0.9,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "oscillator",
    description: "Wood pole resonance: tonal hollow knock that lets the staff ring like wood, not metal.",
    startOffset: 0.01,
    duration: 0.16,
    gain: 0.2,
    attackTime: 0.001,
    decayCurve: "exponential",
    oscillatorType: "triangle",
    frequency: 460,
    sweepEnabled: true,
    frequencyEnd: 300,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "bandpass",
        frequency: 460,
        q: 5.2,
        gain: 0,
      }),
      Object.freeze({
        type: "delay",
        delayTime: 0.03,
        feedback: 0.24,
        mix: 0.18,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Secondary wood knock: delayed lower clocking detail that reinforces the wooden rebound.",
    noiseType: "white",
    startOffset: 0.044,
    duration: 0.045,
    gain: 0.3,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 680,
    q: 5.1,
    sweepEnabled: true,
    frequencyEnd: 340,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "filter",
        filterType: "lowpass",
        frequency: 1600,
        q: 0.9,
        gain: 0,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Dry grain scrape: rough wooden texture after impact, like the staff scraping or flexing slightly.",
    noiseType: "pink",
    startOffset: 0.06,
    duration: 0.12,
    gain: 0.17,
    attackTime: 0.006,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 720,
    q: 3.6,
    sweepEnabled: true,
    frequencyEnd: 360,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.024,
        feedback: 0.08,
        mix: 0.08,
      }),
    ]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Small rebound tick: final light wooden tap from the staff bouncing away.",
    noiseType: "white",
    startOffset: 0.09,
    duration: 0.032,
    gain: 0.15,
    attackTime: 0.001,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 900,
    q: 4.7,
    sweepEnabled: true,
    frequencyEnd: 520,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([]),
  }),
  Object.freeze({
    type: "noise_filter",
    description: "Short dry wooden tail: low rough after-noise so the hit decays like wood instead of metal or flesh.",
    noiseType: "pink",
    startOffset: 0.11,
    duration: 0.13,
    gain: 0.11,
    attackTime: 0.012,
    decayCurve: "exponential",
    filterType: "bandpass",
    frequency: 360,
    q: 2.2,
    sweepEnabled: true,
    frequencyEnd: 180,
    frequencySweep: "exponential",
    reverseBuffer: false,
    muted: false,
    effects: Object.freeze([
      Object.freeze({
        type: "delay",
        delayTime: 0.036,
        feedback: 0.08,
        mix: 0.08,
      }),
    ]),
  }),
]);

export const playStaffHit = (profiles = STAFF_HIT_PROFILES) => {
  playProfileSynth(profiles);
};
