export default Object.freeze({
  arc: Math.PI / 2,
  cooldown: 20,
  criticalChance: 0.1,
  criticalMultiplier: 2,
  damageMax: 4,
  damageMin: 2,
  damageProfile: Object.freeze({ slashing: 1 }),
  damageType: "slashing",
  handedness: "oneHanded",
  duration: 8,
  knockback: 30,
  range: 47,
  staminaCost: 125,
});
